"""Initial migration

Revision ID: 02cf238e8b97
Revises: 
Create Date: 2025-02-02 02:51:21.890214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cf238e8b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('website')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
